version = "0.3"
package = "logo"
license = "GPL"
title = "Simple spatial ABM"
depends = "terrame (>= 2.0)"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements ABM paradigm for spatial models with at most one agent per cell."
