version = "0.4.2"
package = "logo"
license = "GPL"
title = "Simple spatial ABM"
depends = "terrame (>= 2.0)"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = "Implements spatial agent-based models with at most one agent per cell."
